# print("안녕하세요."+"반갑습니다.")
# print("안녕하세요"*5)
# print("안녕하세요"+10) Error 문자열 + 숫자 
print("hello"[0])
# print("hello"[1])
# print("hello"[2])
print("hello"[3])
# print("hello"[4])
# print("hello"[-1])
# print("Hello"[1:3])
# print("Hello"[2:4])
# print("Hello"[:3])
# print("Hello"[2:])
# print("Hello"[100]) # Error out of index (범위를 초과)
print(len("Hello"))